### PR TITLE
Fix permission issue when cache expired

### PR DESCRIPTION
**Pull request by pitan**
If the cache file expires while keep the login session, an error "File open failure" will occur when trying to get user and group IDs. (e.g. id)
So, I modified cache file permission and directory structure it with refer to libstns.

### CODE REVIEW

**Comment by linyows** [comment]
Thank you for P/R. I was aware of this caching privilege issue and it was through octopass as not software that solved the issue for different groups of privileges.

First, I will try to reproduce your case on the weekend.

**Comment by linyows** [comment]
I was able to check this problem. This is certainly a problem, so I will solve it. I'm thinking of creating octopass group and letting write by file owner group rather than dividing cache directory by user. Because I think that the cache will be fully utilized.

**Comment by linyows** [comment]
Hmmm, it refers to the user at the time of group reference, so it's not good.

**Comment by linyows** [comment]
Use setuid in cache read/write.

**Comment by linyows** [comment]
Making daemons to make setuids seems to lose the simplicity of octopass. :sob:

**Comment by pitan** [comment]
Thank you for marge this PR! Do you have plans to update package versions?
https://packagecloud.io/linyows/octopass

**Comment by linyows** [comment]
I released this as v0.7.0.

https://github.com/linyows/octopass/releases/tag/v0.7.0
https://packagecloud.io/linyows/octopass

**Pull request merged**
